// Generated by CoffeeScript 1.6.3
(function() {
  var Blue,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Blue = (function() {
    Blue.NEXT_ID = 10000;

    function Blue(parent) {
      this.parent = parent != null ? parent : null;
      this.grow = __bind(this.grow, this);
      this.color = "blue";
      this.id = Blue.NEXT_ID;
      Blue.NEXT_ID++;
      console.log("Id: " + this.id);
      this.children = [];
    }

    Blue.prototype.grow = function() {
      return this.children = [new Blue(this), new Red(this)];
    };

    return Blue;

  })();

  window.Blue = Blue;

}).call(this);

/*
//@ sourceMappingURL=Blue.map
*/
