// Generated by CoffeeScript 1.6.3
(function() {
  var Blue,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Blue = (function() {
    Blue.NEXT_ID = 10000;

    function Blue() {
      this.accept = __bind(this.accept, this);
      this.grow = __bind(this.grow, this);
      this.color = "blue";
      this.id = Blue.NEXT_ID;
      Blue.NEXT_ID++;
      console.log("Id: " + this.id);
      this.children = [];
    }

    Blue.prototype.grow = function() {
      return this.children = [new Blue(), new Red()];
    };

    Blue.prototype.accept = function(visitor) {
      return visitor.visit(this, this.children);
    };

    return Blue;

  })();

  window.Blue = Blue;

}).call(this);
