// Generated by CoffeeScript 1.6.1
(function() {
  var Layout,
    _this = this;

  Layout = (function() {

    function Layout(width, height, selector) {
      var _this = this;
      this.width = width;
      this.height = height;
      this.selector = selector;
      this._redraw = function() {
        return Layout.prototype._redraw.apply(_this, arguments);
      };
      this._setup = function() {
        return Layout.prototype._setup.apply(_this, arguments);
      };
      this.start = function() {
        return Layout.prototype.start.apply(_this, arguments);
      };
      this.grow = function() {
        return Layout.prototype.grow.apply(_this, arguments);
      };
      this.roots = [new Blue(), new Red(), new Blue(), new Blue(), new Red(), new Red()];
      this.outerLayer = this.roots;
    }

    Layout.prototype.grow = function() {
      var child, firstChild, growth, lastChild, parent, _i, _j, _len, _len1, _ref, _ref1;
      console.log("Grow!");
      growth = [];
      firstChild = null;
      lastChild = null;
      _ref = this.outerLayer;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        parent = _ref[_i];
        _ref1 = parent.grow();
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          child = _ref1[_j];
          if (firstChild == null) {
            firstChild = child;
          }
          growth.push(child);
          lastChild = child;
        }
      }
      return this.outerLayer = growth;
    };

    Layout.prototype.start = function() {
      this._setup();
      return this._redraw();
    };

    Layout.prototype._setup = function() {
      var center, container, edge, gap, i, max, min, p, _i;
      this.physics = new Physics();
      this.height = window.innerHeight;
      this.width = window.innerWidth;
      this.stiffness = 1.0;
      this.spacing = 2.0;
      this.physics.integrator = new Verlet();
      this.physics.viscosity = 0.0001;
      gap = 50.0;
      min = new Vector(-gap, -gap);
      max = new Vector(this.width + gap, this.height + gap);
      edge = new EdgeBounce(min, max);
      center = new Vector(this.width * 0.5, this.height * 0.5);
      console.dir(center);
      for (i = _i = 0; _i <= 100; i = ++_i) {
        p = new Particle(6.0);
        p.colour = 'DC0048';
        p.moveTo(center);
        p.setRadius(1.0);
        p.behaviours.push(edge);
        this.physics.particles.push(p);
      }
      this.renderer = new CanvasRenderer();
      container = $(this.selector);
      container.get(0).appendChild(this.renderer.domElement);
      this.renderer.renderMouse = false;
      this.renderer.init(this.physics);
      return this.renderer.setSize(this.width, this.height);
    };

    Layout.prototype._redraw = function() {
      this.physics.step();
      this.renderer.render(this.physics);
      return requestAnimationFrame(this._redraw);
    };

    return Layout;

  })();

  window.Layout = Layout;

}).call(this);
