// Generated by CoffeeScript 1.6.3
(function() {
  var Red,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Red = (function() {
    Red.NEXT_ID = 0;

    function Red() {
      this.accept = __bind(this.accept, this);
      this.grow = __bind(this.grow, this);
      this.color = "red";
      this.id = Red.NEXT_ID;
      Red.NEXT_ID++;
      console.log("Id: " + this.id);
      this.children = [];
    }

    Red.prototype.grow = function() {
      return this.children = [new Blue()];
    };

    Red.prototype.accept = function(visitor) {
      return visitor.visit(this, this.children);
    };

    return Red;

  })();

  window.Red = Red;

}).call(this);

/*
//@ sourceMappingURL=Red.map
*/
